vich_uploader:
    db_driver: orm

    mappings:
       featured_images:
           uri_prefix: /images/featured_images
           upload_destination: '%kernel.project_dir%/public/images/featured_images'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
